// task-finder/src/App.vue
<template>
  <div class="flex min-h-screen flex-col bg-bg">
    <main class="flex-1 overflow-y-auto pb-tabbar">
      <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </main>
    <TabBar />
    <UpdateOverlay />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import TabBar from './components/TabBar.vue';
import UpdateOverlay from './components/UpdateOverlay.vue';
import { initNative } from './composables/useNative';
import { initDeepLinks } from './composables/useDeepLinks';
import { useOta } from './composables/useOta';

const router = useRouter();
const { startAutoUpdate } = useOta();

onMounted(() => {
  initNative();
  initDeepLinks(router);
  // App-wide OTA poller. Runs regardless of which tab is active so a user
  // stuck on the Sandbox tab still receives hot updates.
  startAutoUpdate(15_000);
});
</script>

<style scoped>
/* Vue <transition> hooks — Tailwind can't express these directly. */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.15s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// src/App.tsx
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import AppRoutes from './router';
import TabBar from './components/TabBar';
import UpdateOverlay from './components/UpdateOverlay';
import { initNative } from './composables/useNative';
import { initDeepLinks } from './composables/useDeepLinks';
import { useOta } from './composables/useOta';

export default function App() {
  const navigate = useNavigate();
  const { startAutoUpdate } = useOta();

  useEffect(() => {
    initNative();
    initDeepLinks(navigate);
    // App-wide OTA poller. Runs regardless of which tab is active so a user
    // stuck on the Sandbox tab still receives hot updates.
    startAutoUpdate(15_000);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="flex min-h-screen flex-col bg-bg">
      <main className="flex-1 overflow-y-auto pb-tabbar">
        <AppRoutes />
      </main>
      <TabBar />
      <UpdateOverlay />
    </div>
  );
}
